import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const labels={bed:'儲物床架',bedding:'床墊與靠墊',wardrobe:'衣櫃',desk:'摺枱與編織凳',rug:'編織地蓆',decor:'茶具、書本與擺設',kitchen:'廚櫃與檯面',fridge:'小雪櫃',hob:'電磁爐',extractor:'抽油煙機',bathroom:'浴室管件與地磚',toilet:'座廁',vanity:'洗手盆與鏡櫃',curtain:'浴簾',windows:'窗框、障子與竹簾',doors:'門片與門框',lamps:'燈具',outerWalls:'前方與右側牆',partitions:'廚廁分隔牆',ceiling:'天花'};
const sections=[['家具與生活',['bed','bedding','wardrobe','desk','rug','decor']],['廚房與浴室',['kitchen','fridge','hob','extractor','bathroom','toilet','vanity','curtain']],['門窗與結構',['windows','doors','lamps','outerWalls','partitions','ceiling']]];
const defaultVisible=Object.fromEntries(Object.keys(labels).map(k=>[k,!['outerWalls','partitions','ceiling'].includes(k)]));
const state={style:'japanese',time:10,brightness:100,lights:true,view:'overview',cutaway:true,autoRotate:false,visible:{...defaultVisible},ready:false};
for(const [title,keys] of sections){const d=document.createElement('details');d.className='object-group';d.open=title==='家具與生活';d.innerHTML=`<summary>${title}</summary>`;for(const k of keys){const l=document.createElement('label');l.className='switch-row';l.innerHTML=`<span>${labels[k]}</span><input type="checkbox" role="switch" data-object="${k}" aria-label="顯示${labels[k]}" ${state.visible[k]?'checked':''}>`;d.append(l)}$('#objects').append(d)}
let renderer,scene,camera,orbit,model;const groups=new Map(),materials=[];let noticeTimer;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function notice(text){$('#notice').textContent=text;$('#notice').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('show'),2200)}
function fail(e){console.error(e);$('#load-label').textContent='暫時無法顯示 3D 模型';$('#load-detail').textContent='請檢查網絡，並使用支援 WebGL 的新版瀏覽器。';$('#load-progress').hidden=true;$('#retry').hidden=false;$('#retry').onclick=()=>location.reload()}
const timeText=t=>`${String(Math.floor(t)).padStart(2,'0')}:${String(Math.round(t%1*60)).padStart(2,'0')}`;
const palettes={japanese:{label:'日式深木',wood:'#795438',floor:'#bea078',ivory:'#eee7d9',olive:'#767743',sage:'#a0a181',ochre:'#c29842',indigo:'#283f58',tile:'#697746',rug:'#b9a878'},muji:{label:'Muji 淺木',wood:'#c4a477',floor:'#d3ba94',ivory:'#f4f0e7',olive:'#b5b1a2',sage:'#d3cdbd',ochre:'#c4b38c',indigo:'#777d75',tile:'#c7cab9',rug:'#c5b78f'},nordic:{label:'北歐',wood:'#b59571',floor:'#cbb498',ivory:'#f1f2ec',olive:'#607f8c',sage:'#c7d2d0',ochre:'#cd8762',indigo:'#314d65',tile:'#709394',rug:'#c1b7a4'}};
function texture(kind){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#eee';ctx.fillRect(0,0,256,256);let seed=15;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};if(kind==='wood'){for(let i=0;i<440;i++){ctx.strokeStyle=`rgba(55,43,27,${.015+rnd()*.09})`;ctx.lineWidth=.4+rnd()*1.1;const y=rnd()*256;ctx.beginPath();ctx.moveTo(0,y);ctx.bezierCurveTo(70,y+rnd()*9,180,y-rnd()*9,256,y+rnd()*4);ctx.stroke()}}else{for(let i=0;i<256;i+=4){ctx.fillStyle=i%8?'#d9d9d9':'#f5f5f5';ctx.fillRect(i,0,1,256);ctx.fillRect(0,i,256,1)}}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.repeat.set(kind==='wood'?1:10,kind==='wood'?2:10);return t}
const woodTex=texture('wood'),clothTex=texture('cloth');
function materialKind(n){if(/smoked|wood|bamboo/i.test(n)&&!/look/i.test(n))return 'wood';if(/Light oak floor/i.test(n))return 'floor';if(/Warm ivory mineral/i.test(n))return 'ivory';if(/Olive waffle/i.test(n))return 'olive';if(/Sage linen/i.test(n))return 'sage';if(/Mustard/i.test(n))return 'ochre';if(/Deep indigo/i.test(n))return 'indigo';if(/Olive glazed/i.test(n))return 'tile';if(/Woven rush/i.test(n))return 'rug';return null}
function category(o){let k=o.userData.category||o.parent?.userData.category||'decor',n=o.userData.displayName||o.name;if(k==='kitchen'){if(/fridge/i.test(n))k='fridge';else if(/hob/i.test(n))k='hob';else if(/extractor/i.test(n))k='extractor'}if(k==='bathroom'){if(/Toilet/i.test(n))k='toilet';else if(/basin|vanity|mirror|soap/i.test(n))k='vanity';else if(/curtain/i.test(n))k='curtain'}return k}
function applyStyle(key,announce=true){if(!palettes[key])throw Error('Unknown style');state.style=key;const p=palettes[key];for(const m of materials){const kind=m.userData.kind;if(kind&&p[kind])m.color.set(p[kind]);}$$('[data-style]').forEach(b=>{const a=b.dataset.style===key;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a)});$('#style-label').textContent=p.label;updateCaption();if(announce)notice(`已切換至${p.label}`)}
let sun,ambient,hemi,practicals=[],ground;
function setTime(t){t=Number(t);if(!Number.isFinite(t)||t<0||t>23.75)throw Error('Invalid time');state.time=t;$('#time').value=t;const h=timeText(t);$('#time-value').textContent=h;$('#time-name').textContent=t<5||t>=20?'寧靜夜晚':t<8?'柔和晨光':t<12?'明亮上午':t<16?'午後日光':t<19?'暖色黃昏':'入夜時分';updateLighting();updateCaption()}
function updateLighting(){if(!sun)return;const t=state.time,day=Math.max(0,Math.sin((t-6)/12*Math.PI)),b=state.brightness/100;sun.intensity=day*3*b;sun.position.set(Math.cos((t-6)/12*Math.PI)*7,Math.max(.5,day*9),-5);sun.color.set(day<.5?'#ffd5a2':'#fff4df');hemi.intensity=(.38+day*1.25)*b;hemi.color.set(day>.05?'#dae7f3':'#6a819d');ambient.intensity=(.14+day*.17)*b;for(const l of practicals)l.intensity=state.lights&&state.visible.lamps?(1-day*.65)*l.userData.power*b:0;for(const m of materials)if(m.userData.lamp&&m.emissive){m.emissive.set('#ffe0a0');m.emissiveIntensity=state.lights?(1-day*.6)*.65:0;}const bg=new THREE.Color().lerpColors(new THREE.Color('#313d4a'),new THREE.Color('#e8e6df'),Math.min(1,day*1.6+.12));scene.background=bg;scene.fog.color.copy(bg);ground.material.color.copy(bg).multiplyScalar(.93);$('.stage').style.background=bg.getStyle();$('.scene-caption').style.color=day>.2?'#29392e':'#f1eee5';$('#model-status').style.color=day>.2?'#63705e':'#c5d0cb';$('.gesture').style.color=day>.2?'#63705e':'#c5d0cb';renderer.toneMappingExposure=.95}
function updateCaption(){$('#scene-caption').innerHTML=`${palettes[state.style].label} <span>·</span> ${timeText(state.time)}`}
function setVisible(key,value,announce=false){if(!(key in labels)||typeof value!=='boolean')throw Error('Invalid visibility');state.visible[key]=value;groups.get(key)?.forEach(o=>o.visible=value);const el=$(`[data-object="${key}"]`);if(el)el.checked=value;updateCount();if(key==='lamps')updateLighting();if(announce)notice(`${value?'顯示':'隱藏'}${labels[key]}`)}
function updateCount(){if(!state.ready)return;const visible=Object.keys(labels).filter(k=>state.visible[k]&&groups.has(k)).length;$('#model-status').textContent=`${visible} 組物件顯示中`;$('#model-status').dataset.visibleGroups=visible}
function shell(cutaway,announce=true){state.cutaway=cutaway;for(const k of ['outerWalls','partitions','ceiling'])setVisible(k,!cutaway);$('#shell').setAttribute('aria-pressed',cutaway);$('#shell').textContent=cutaway?'剖開模式':'完整空間';if(announce)notice(cutaway?'已剖開牆身與天花':'已恢復完整空間')}
const views={overview:{p:[6.4,7.1,6.5],t:[.3,.6,-1.9]},living:{p:[1.05,1.4,-.28],t:[1.18,1.25,-3.7]},kitchen:{p:[-.05,1.55,-1.82],t:[-1.05,1.0,-2.78]},bathroom:{p:[.02,1.45,-.8],t:[-1.05,.8,-.65]},top:{p:[.3,10,-1.89],t:[.3,0,-1.9]}};let transition=null;
function setView(key){if(!views[key])throw Error('Unknown view');state.view=key;const v=views[key];if(['overview','top'].includes(key))shell(true,false);else{shell(false,false);setVisible('ceiling',false)}orbit.minDistance=['overview','top'].includes(key)?2:.3;orbit.maxDistance=18;transition={from:camera.position.clone(),targetFrom:orbit.target.clone(),to:new THREE.Vector3(...v.p),targetTo:new THREE.Vector3(...v.t),start:performance.now()};if(reduced){camera.position.copy(transition.to);orbit.target.copy(transition.targetTo);transition=null;orbit.update()}$$('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===key);b.setAttribute('aria-pressed',b.dataset.view===key)})}
function rotate(amount){transition=null;const offset=camera.position.clone().sub(orbit.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),amount);camera.position.copy(orbit.target).add(offset);orbit.update()}
function zoom(scale){transition=null;const off=camera.position.clone().sub(orbit.target),d=THREE.MathUtils.clamp(off.length()*scale,orbit.minDistance,orbit.maxDistance);camera.position.copy(orbit.target).add(off.setLength(d));orbit.update()}
function reset(){state.brightness=100;state.lights=true;state.autoRotate=false;$('#brightness').value=100;$('#brightness-value').textContent='100%';$('#lights').checked=true;$('#auto-rotate').setAttribute('aria-pressed',false);orbit.autoRotate=false;for(const k in defaultVisible)setVisible(k,defaultVisible[k]);applyStyle('japanese',false);setTime(10);setView('overview');notice('已恢復初始設計')}
function init(){try{renderer=new THREE.WebGLRenderer({canvas:$('#canvas'),antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;scene=new THREE.Scene();scene.background=new THREE.Color('#e8e6df');scene.fog=new THREE.Fog('#e8e6df',18,42);camera=new THREE.PerspectiveCamera(42,1,.03,100);camera.position.fromArray(views.overview.p);orbit=new OrbitControls(camera,renderer.domElement);orbit.target.fromArray(views.overview.t);orbit.enableDamping=true;orbit.dampingFactor=.07;orbit.maxPolarAngle=Math.PI*.495;orbit.minDistance=2;orbit.maxDistance=18;orbit.autoRotateSpeed=.6;orbit.addEventListener('start',()=>{transition=null});ambient=new THREE.AmbientLight('#fff3de',.2);hemi=new THREE.HemisphereLight('#dae7f3','#74634f',1.5);scene.add(ambient,hemi);sun=new THREE.DirectionalLight('#fff4df',2.7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.5,far:30});sun.shadow.normalBias=.035;sun.shadow.bias=-.00015;sun.target.position.set(.3,0,-2);scene.add(sun,sun.target);for(const [p,power]of[[[1.14,2.20,-2.69],10],[[2.12,1.34,-3.26],3], [[-1.36,1.56,-2.17],5],[[-.46,1.8,-.23],4]]){const l=new THREE.PointLight('#ffd193',power,6,2);l.position.fromArray(p);l.userData.power=power;practicals.push(l);scene.add(l)}ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#dedbd1',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.15;ground.receiveShadow=true;scene.add(ground);new ResizeObserver(resize).observe($('#stage'));resize();updateLighting();renderer.setAnimationLoop(animate);new GLTFLoader().load('./assets/room.glb',loaded,p=>{if(p.total){$('#load-progress').value=p.loaded/p.total*100;$('#load-detail').textContent=`載入家具與材質… ${Math.round(p.loaded/p.total*100)}%`}},fail)}catch(e){fail(e)}}
function loaded(gltf){try{model=gltf.scene;model.updateMatrixWorld(true);const buckets=new Map();model.traverse(o=>{if(!o.isMesh)return;const group=category(o),sources=Array.isArray(o.material)?o.material:[o.material];if(sources.length!==1)return;const mat=sources[0],key=group+'|'+mat.uuid;let bucket=buckets.get(key);if(!bucket){const m=mat.clone();m.userData.kind=materialKind(m.name);m.userData.lamp=/Washi lamp shade/i.test(m.name);if(['wood','floor'].includes(m.userData.kind)){m.map=woodTex;m.roughness=.68;}else if(['olive','sage','ochre','indigo','rug'].includes(m.userData.kind)){m.map=clothTex;m.bumpMap=clothTex;m.bumpScale=.002;m.roughness=.96;}if(/glazing/i.test(m.name)){m.transparent=true;m.opacity=.18;m.depthWrite=false;if('transmission'in m)m.transmission=0;}if(/shoji/i.test(m.name)){m.side=THREE.DoubleSide;m.color.set('#f1e7cf');m.roughness=.9;}materials.push(m);bucket={group,material:m,geometries:[]};buckets.set(key,bucket)}const geo=o.geometry.clone();geo.applyMatrix4(o.matrixWorld);for(const name of Object.keys(geo.attributes))if(!['position','normal','uv'].includes(name))geo.deleteAttribute(name);if(!geo.attributes.normal)geo.computeVertexNormals();if(!geo.attributes.uv)geo.setAttribute('uv',new THREE.BufferAttribute(new Float32Array(geo.attributes.position.count*2),2));const flat=geo.index?geo.toNonIndexed():geo;bucket.geometries.push(flat)});for(const bucket of buckets.values()){const geo=mergeGeometries(bucket.geometries,false);if(!geo)throw Error('Could not assemble model');const mesh=new THREE.Mesh(geo,bucket.material);mesh.name=bucket.group;mesh.userData.category=bucket.group;mesh.castShadow=!/glazing|shoji/i.test(bucket.material.name);mesh.receiveShadow=true;scene.add(mesh);if(!groups.has(bucket.group))groups.set(bucket.group,[]);groups.get(bucket.group).push(mesh);mesh.visible=state.visible[bucket.group]??true;bucket.geometries.forEach(g=>g.dispose())}state.ready=true;applyStyle('japanese',false);updateLighting();updateCount();$('#controls').disabled=false;$('#loader').hidden=true;document.body.dataset.modelLoaded='true';document.body.dataset.meshBatches=buckets.size;for(const [k]of Object.entries(labels)){if(!groups.has(k))$(`[data-object="${k}"]`).closest('label').hidden=true}registerTools();}catch(e){fail(e)}}
function resize(){if(!renderer)return;const r=$('#stage').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
async function loadCompressedModel(){
  const parts=await Promise.all(['01','02'].map(async n=>{const r=await fetch(`./assets/room.glb.gz.part-${n}.txt`);if(!r.ok)throw Error(`Model part ${n} unavailable`);return r.text()}));
  const raw=atob(parts.join('')),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);
  if(!window.DecompressionStream)throw Error('This browser cannot decompress the model asset');
  const inflated=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).blob(),url=URL.createObjectURL(inflated),loader=new GLTFLoader();
  loader.load(url,g=>{URL.revokeObjectURL(url);loaded(g)},p=>{if(p.total){$('#load-progress').value=p.loaded/p.total*100;$('#load-detail').textContent=`載入家具與材質… ${Math.round(p.loaded/p.total*100)}%`}},e=>{URL.revokeObjectURL(url);fail(e)})
}
function animate(){if(transition){const t=Math.min(1,(performance.now()-transition.start)/650),e=1-Math.pow(1-t,3);camera.position.lerpVectors(transition.from,transition.to,e);orbit.target.lerpVectors(transition.targetFrom,transition.targetTo,e);if(t===1)transition=null;}orbit.update();renderer.render(scene,camera)}
$$('[data-style]').forEach(b=>b.onclick=()=>applyStyle(b.dataset.style));$$('[data-time]').forEach(b=>b.onclick=()=>setTime(b.dataset.time));$$('[data-view]').forEach(b=>b.onclick=()=>{if(state.ready)setView(b.dataset.view)});$$('[data-object]').forEach(i=>i.onchange=()=>setVisible(i.dataset.object,i.checked));$('#time').oninput=e=>setTime(e.target.value);$('#lights').onchange=e=>{state.lights=e.target.checked;updateLighting()};$('#brightness').oninput=e=>{state.brightness=+e.target.value;$('#brightness-value').textContent=state.brightness+'%';updateLighting()};$('#shell').onclick=()=>{if(state.ready)shell(!state.cutaway)};$('#reset').onclick=()=>{if(state.ready)reset()};$('#restore-objects').onclick=()=>{for(const k in defaultVisible)setVisible(k,defaultVisible[k]);shell(true,false);notice('家具已恢復顯示')};$('#rotate-left').onclick=()=>rotate(.23);$('#rotate-right').onclick=()=>rotate(-.23);$('#zoom-in').onclick=()=>zoom(.82);$('#zoom-out').onclick=()=>zoom(1.22);$('#auto-rotate').onclick=()=>{state.autoRotate=!state.autoRotate;orbit.autoRotate=state.autoRotate;$('#auto-rotate').setAttribute('aria-pressed',state.autoRotate)};$('#canvas').addEventListener('keydown',e=>{if(!state.ready)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')rotate(.17);else if(e.key==='ArrowRight')rotate(-.17);else zoom(['ArrowUp','+','='].includes(e.key)?.88:1.14)}});
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const abort=new AbortController();const tools=[{name:'read_room_design',description:'Read the current visible room style, time, lighting and furniture visibility.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>structuredClone(state)},{name:'configure_room_design',description:'Change the room style, time of day, camera and furniture visibility using the same controls as the page.',inputSchema:{type:'object',properties:{style:{enum:Object.keys(palettes)},time:{type:'number',minimum:0,maximum:23.75},view:{enum:Object.keys(views)},visibility:{type:'object',properties:Object.fromEntries(Object.keys(labels).map(k=>[k,{type:'boolean'}])),additionalProperties:false}},additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object')throw Error('Invalid input');for(const k of Object.keys(input))if(!['style','time','view','visibility'].includes(k))throw Error('Unknown field');if(input.style&&!palettes[input.style])throw Error('Unknown style');if(input.time!==undefined&&(!Number.isFinite(input.time)||input.time<0||input.time>23.75))throw Error('Invalid time');if(input.view&&!views[input.view])throw Error('Unknown view');if(input.visibility){for(const [k,v]of Object.entries(input.visibility))if(!(k in labels)||typeof v!=='boolean')throw Error('Invalid visibility')}if(input.style)applyStyle(input.style,false);if(input.time!==undefined)setTime(input.time);if(input.view)setView(input.view);if(input.visibility)for(const [k,v]of Object.entries(input.visibility))setVisible(k,v);return structuredClone(state)}}];for(const t of tools){try{Promise.resolve(context.registerTool(t,{signal:abort.signal})).catch(()=>{})}catch{}}addEventListener('pagehide',()=>abort.abort(),{once:true})}
const originalFetch=globalThis.fetch.bind(globalThis);
globalThis.fetch=async(input,init)=>{const url=typeof input==='string'?input:input.url;if(!/\/assets\/room\.glb$/.test(url))return originalFetch(input,init);const parts=await Promise.all(['01','02'].map(n=>originalFetch(`./assets/room.glb.gz.part-${n}.txt`).then(r=>{if(!r.ok)throw Error(`Model part ${n} unavailable`);return r.text()})),encoded=(await Promise.all(parts)).join(''),raw=atob(encoded),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);if(!globalThis.DecompressionStream)throw Error('This browser cannot decompress the model asset');const inflated=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();return new Response(inflated,{status:200,headers:{'Content-Type':'model/gltf-binary'}})};
init();
